schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/oauthlib"
description = "kaiju from-scratch implementation task for oauthlib/oauthlib."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/oauthlib"
instance_id = "kaiju/oauthlib"
base_commit = "228f9d3cce7b32099972e39639f2d5369cf07628"
reference_commit = "a2779c65b3e961f1b49c05a2417c0ae819f3f8c4"
src_dir = "oauthlib"
python_version = "3.9"
test_mode = "official_test_ids"
n_test_ids = 683

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_oauthlib_oauthlib"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
