schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/erg"
description = "kaiju from-scratch implementation task for erg-lang/erg."
keywords = ["kaiju", "code-generation", "rust", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/erg"
instance_id = "kaiju/erg"
base_commit = "faba6bedfd67bfbe90aa958f43f81ba7228fd37b"
reference_commit = "b8bc4e33eb23246566f08c9efd3916ebd41c1f3f"
src_dir = "src"
rust_version = "stable"
test_mode = "official_test_ids"
n_test_ids = 215

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:rust_erg_lang_erg_faba6be"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
