schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/riker"
description = "kaiju from-scratch implementation task for riker-rs/riker."
keywords = ["kaiju", "code-generation", "rust", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/riker"
instance_id = "kaiju/riker"
base_commit = "20fa4d22f50fa5463701413b941416ef81c92628"
reference_commit = "ccd4e5f76f12e5d409c6dcf7e03401391e06b550"
src_dir = "src"
rust_version = "stable"
test_mode = "official_test_ids"
n_test_ids = 26

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:rust_riker_rs_riker"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
