schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/datasketch"
description = "kaiju from-scratch implementation task for ekzhu/datasketch."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/datasketch"
instance_id = "kaiju/datasketch"
base_commit = "b97eb128d016f10e3164857a16179f51720b2308"
reference_commit = "3da96a591c954952c9dd367567db720cfdc151e0"
src_dir = "datasketch"
python_version = "3.9"
test_mode = "official_test_ids"
n_test_ids = 262

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_ekzhu_datasketch"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
