schema_version = "1.3"
source = "commit0"

[task]
name = "distribution/distribution_go"
description = "commit0 from-scratch implementation task for distribution/distribution."
keywords = ["commit0", "code-generation", "go", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "distribution/distribution"
instance_id = "distribution_distribution_go"
base_commit = "157c493044ac794a61d977091b0016ee38977525"
reference_commit = "472c9d38c9fc523599f37ca3207279e5ab10f74f"
src_dir = "."
go_version = "1.25.0"
test_mode = "official_test_ids"
n_test_ids = 309

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:go_distribution_distribution"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
