schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/uuid"
description = "kaiju from-scratch implementation task for google/uuid."
keywords = ["kaiju", "code-generation", "go", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Shivansh9411/uuid"
instance_id = "kaiju/uuid"
base_commit = "e91597e7a9265650a29369b5633c798d917e5199"
reference_commit = "2d3c2a9cc518326daf99a383f07c4d3c44317e4d"
src_dir = "."
go_version = "1.19"
test_mode = "official_test_ids"
n_test_ids = 46

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:go_google_uuid"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
