schema_version = "1.3"
source = "commit0"

[task]
name = "open-telemetry/opentelemetry-collector_go"
description = "commit0 from-scratch implementation task for open-telemetry/opentelemetry-collector."
keywords = ["commit0", "code-generation", "go", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "open-telemetry/opentelemetry-collector"
instance_id = "open-telemetry_opentelemetry-collector_go"
base_commit = "5359ead9b1548f7420f6feba1062f3b0bace4df0"
reference_commit = "0cba399419ac5bc738a2986874f7c5ee3b7b7e70"
src_dir = "."
go_version = "1.25.0"
test_mode = "official_test_ids"
n_test_ids = 17

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:opentelemetry-collector"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
