schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/SpectralCluster"
description = "kaiju from-scratch implementation task for wq2012/SpectralCluster."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/SpectralCluster"
instance_id = "kaiju/SpectralCluster"
base_commit = "91210be045717ad3614f1ec8ddc0c92b8c7cc01e"
reference_commit = "f00d5d7ee6aa3e61b18922597010595c32ca0dea"
src_dir = "spectralcluster"
python_version = "3.8"
test_mode = "official_test_ids"
n_test_ids = 77

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_wq2012_spectralcluster_91210be"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
