schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/goleak"
description = "kaiju from-scratch implementation task for uber-go/goleak."
keywords = ["kaiju", "code-generation", "go", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Shivansh9411/goleak"
instance_id = "kaiju/goleak"
base_commit = "c9075a466fdfdef715e02e92d958967cf1a40edd"
reference_commit = "5f791e3ef83b35d32b262466250507c2f20fea3c"
src_dir = "."
go_version = "1.20"
test_mode = "official_test_ids"
n_test_ids = 20

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:go_uber_go_goleak_c9075a4"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
