schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/graphql-jit"
description = "kaiju from-scratch implementation task for zalando-incubator/graphql-jit."
keywords = ["kaiju", "code-generation", "typescript", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/graphql-jit"
instance_id = "kaiju/graphql-jit"
base_commit = "4289f484cd98e0cb569db43c1b9a4372108a0a3d"
reference_commit = "61e5a006156f6c95e9a3246715a135da93216342"
src_dir = "src"
node_version = "22"
test_mode = "official_test_ids"
n_test_ids = 396

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:typescript_zalando_incubator_graphql_jit"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
