schema_version = "1.3"
source = "commit0"

[task]
name = "commit-0/futures-signals"
description = "commit0 from-scratch implementation task for Pauan/rust-signals."
keywords = ["commit0", "code-generation", "rust", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Pauan/rust-signals"
instance_id = "commit-0/futures-signals"
base_commit = "4cd84d457cdc2f6eec0d7e81522bdf56402f7da1"
reference_commit = "006adaf5b13870c6cec71a2f00fda0d12f1e3b5d"
src_dir = "src"
rust_version = "stable"
test_mode = "official_test_ids"
n_test_ids = 114

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:rust_pauan_rust_signals"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
