schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/btclib"
description = "kaiju from-scratch implementation task for btclib-org/btclib."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/btclib"
instance_id = "kaiju/btclib"
base_commit = "fe5cb942954e2645f2f7b65c5367634dbbc306fa"
reference_commit = "600cb1365781aa7dadcfb1e58a449db0e2d0a1f6"
src_dir = "btclib"
python_version = "3.11"
test_mode = "official_test_ids"
n_test_ids = 297

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_btclib_org_btclib"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
