schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/rollup-plugin-typescript2"
description = "kaiju from-scratch implementation task for ezolenko/rollup-plugin-typescript2."
keywords = ["kaiju", "code-generation", "typescript", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/rollup-plugin-typescript2"
instance_id = "kaiju/rollup-plugin-typescript2"
base_commit = "f451cc6769cb9d400d1e3de1c9eab444e0ec77c4"
reference_commit = "60793113fcd326ab9e45b4f46b2956be0b2ab4b1"
src_dir = "src"
node_version = "20"
test_mode = "official_test_ids"
n_test_ids = 44

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:typescript_ezolenko_rollup_plugin_typescript2"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
