schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/bigcache"
description = "kaiju from-scratch implementation task for allegro/bigcache."
keywords = ["kaiju", "code-generation", "go", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Shivansh9411/bigcache"
instance_id = "kaiju/bigcache"
base_commit = "e035633471d066a1d005b5f474f74f20a490c7a6"
reference_commit = "532eb6410aefb749509084c74f56b8313e200f4a"
src_dir = "."
go_version = "1.16"
test_mode = "official_test_ids"
n_test_ids = 91

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:go_allegro_bigcache"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
