schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/pymonad"
description = "kaiju from-scratch implementation task for jasondelaat/pymonad."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Shivansh9411/pymonad"
instance_id = "kaiju/pymonad"
base_commit = "f76f7e5f6dbeac2fec463ff6b36870544fbae3ba"
reference_commit = "9681c15da2321dc29d093d796b8f5c7a85153339"
src_dir = "pymonad"
python_version = "3.7"
test_mode = "official_test_ids"
n_test_ids = 240

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_jasondelaat_pymonad_f76f7e5"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
