schema_version = "1.3"
source = "commit0"

[task]
name = "commit-0/refactor"
description = "commit0 from-scratch implementation task for isidentical/refactor."
keywords = ["commit0", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "isidentical/refactor"
instance_id = "commit-0/refactor"
base_commit = "6b5d9f753b9257add01902929252d1be1bf4f8e2"
reference_commit = "609a5b2011b25bcba177a0132865f2bb49e369d3"
src_dir = "refactor"
python_version = "3.9"
test_mode = "official_test_ids"
n_test_ids = 139

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_isidentical_refactor"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
