schema_version = "1.3"
source = "kaiju"

[task]
name = "kaiju/kui"
description = "kaiju from-scratch implementation task for abersheeran/kui."
keywords = ["kaiju", "code-generation", "python", "swe"]

[metadata]
category = "code-generation"
difficulty = "hard"
original_repo = "Zahgon/kui"
instance_id = "kaiju/kui"
base_commit = "e1f5ce5506cfa3b35e37103b9d0895d5e83b1db0"
reference_commit = "83daa32a6621762a7891a9bcc65de05f148ca5d8"
src_dir = "kui"
python_version = "3.9"
test_mode = "official_test_ids"
n_test_ids = 100

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[environment]
docker_image = "426628337772.dkr.ecr.ap-south-1.amazonaws.com/kaiju_q2:python_abersheeran_kui"
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 4096
network_mode = "public"
workdir = "/testbed"
